name: Lets run tests

on:
  push:
    branches: [main]  

jobs:
  test:
    name: Run Application tests
    runs-on: ubuntu-latest                        
    steps:
    - name: Checkout application code
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@master
      with:
        node-version: 18
        cashe: “npm”
    - name: Install Dependencies
      run: npm install
    - name: Run Jest tests
      run: |
        npm run test:cov
        npm run test:e2e